# Generated by Django 5.0.4 on 2024-07-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0003_cartitem_alter_cart_food_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='food_item',
            new_name='food',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='food_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartitem',
            field=models.ManyToManyField(related_name='carts', to='orderfood.cartitem'),
        ),
        migrations.DeleteModel(
            name='OrderFood',
        ),
    ]
