# Generated by Django 5.0.4 on 2024-07-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0004_rename_food_item_cartitem_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0.0),
        ),
    ]
