# Generated by Django 5.0.4 on 2024-05-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_userfavouriteroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
    ]
