# Generated by Django 5.0.4 on 2024-05-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_roomimage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
