# Generated by Django 5.0.4 on 2024-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='name',
            field=models.CharField(blank=True, default='room', max_length=200, null=True),
        ),
    ]
