# Generated by Django 5.0.4 on 2024-05-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_roomimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='main_image',
            field=models.ImageField(default='static/images/room.jpeg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(default='static/images/room.jpeg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
