# Generated by Django 5.0.4 on 2024-05-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_main_image_alter_roomimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='room_gallery', to='rooms.roomimage'),
        ),
        migrations.AlterField(
            model_name='room',
            name='main_image',
            field=models.ImageField(default='/static/images/room.jpeg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(default='/static/images/room.jpeg', upload_to='uploads/'),
        ),
    ]
