# Generated by Django 5.0.4 on 2024-07-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_userfavouriterestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
