# Generated by Django 5.0.4 on 2024-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestaurantbooking',
            name='checkin_time',
            field=models.TimeField(),
        ),
    ]
