# Generated by Django 5.0.4 on 2024-07-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_userrestaurantbooking_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
